### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by kplaxmaster** [stephenmcd/gnotty#19]
Can't install from pip or from github (python setup.py install).

error: paver-minilib.zip: No such file or directory

**Comment by orotau** [comment]
Hi Stephen
I get the same error as kplaxmaster (stacktrace follows) when trying to install gnotty using 
pip install -U gnotty
The suggested workaround works for me
g

Downloading/unpacking gnotty
  Downloading Gnotty-0.2.6.tar.gz (299kB): 299kB downloaded
  Running setup.py (path:/home/graham/Virtual-Environments/readme-work/build/gnotty/setup.py) egg_info for package gnotty
    
    warning: no previously-included files matching '*' found under directory 'docs/build'
Downloading/unpacking gevent-socketio==0.3.5-beta (from gnotty)
  Downloading gevent-socketio-0.3.5-beta.tar.gz
  Running setup.py (path:/home/graham/Virtual-Environments/readme-work/build/gevent-socketio/setup.py) egg_info for package gevent-socketio
    
    Installed /home/graham/Virtual-Environments/readme-work/build/gevent-socketio/versiontools-1.9.1-py2.7.egg
    
    warning: no previously-included files found matching 'socketio/.ropeproject/*'
    warning: no previously-included files found matching 'socketio/sample_protocol_for_doc.py'
Downloading/unpacking irc==2.0 (from gnotty)
  Downloading irc-2.0.zip (106kB): 106kB downloaded
  Running setup.py (path:/home/graham/Virtual-Environments/readme-work/build/irc/setup.py) egg_info for package irc
    Searching for hgtools
    Reading https://pypi.python.org/simple/hgtools/
    Best match: hgtools 6.3
    Downloading https://pypi.python.org/packages/source/h/hgtools/hgtools-6.3.zip#md5=584d74b81b1efae3604c53086d1a3acb
    Processing hgtools-6.3.zip
    Writing /tmp/easy_install-c3XG1W/hgtools-6.3/setup.cfg
    Running hgtools-6.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-c3XG1W/hgtools-6.3/egg-dist-tmp-TfBhF0
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/graham/Virtual-Environments/readme-work/build/irc/setup.py", line 10, in <module>
        paver.tasks.main()
      File "paver-minilib.zip/paver/tasks.py", line 808, in main
      File "paver-minilib.zip/paver/tasks.py", line 786, in _launch_pavement
      File "paver-minilib.zip/paver/tasks.py", line 739, in _process_commands
      File "paver-minilib.zip/paver/tasks.py", line 653, in _parse_command_line
      File "paver-minilib.zip/paver/tasks.py", line 611, in _preparse
      File "paver-minilib.zip/paver/tasks.py", line 107, in get_task
      File "paver-minilib.zip/paver/setuputils.py", line 167, in get_task
      File "paver-minilib.zip/paver/setuputils.py", line 195, in _get_distribution
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 580, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 818, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 830, in obtain
        return installer(requirement)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 593, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 809, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1015, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1000, in run_setup
        run_setup(setup_script, args)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 47, in run_setup
        working_set.__init__()
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 430, in __init__
        self.add_entry(entry)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 444, in add_entry
        for dist in find_distributions(entry, True):
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 1745, in find_eggs_in_zip
        metadata = EggMetadata(importer)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 1710, in __init__
        self.zipinfo = build_zipmanifest(importer.archive)
      File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 1477, in build_zipmanifest
        zfile = zipfile.ZipFile(path)
      File "/usr/lib/python2.7/zipfile.py", line 756, in __init__
        self.fp = open(file, modeDict[mode])
    IOError: [Errno 2] No such file or directory: 'paver-minilib.zip'
    Complete output from command python setup.py egg_info:
    Searching for hgtools

Reading https://pypi.python.org/simple/hgtools/

Best match: hgtools 6.3

Downloading https://pypi.python.org/packages/source/h/hgtools/hgtools-6.3.zip#md5=584d74b81b1efae3604c53086d1a3acb

Processing hgtools-6.3.zip

Writing /tmp/easy_install-c3XG1W/hgtools-6.3/setup.cfg

Running hgtools-6.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-c3XG1W/hgtools-6.3/egg-dist-tmp-TfBhF0

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/graham/Virtual-Environments/readme-work/build/irc/setup.py", line 10, in <module>

    paver.tasks.main()

  File "paver-minilib.zip/paver/tasks.py", line 808, in main

  File "paver-minilib.zip/paver/tasks.py", line 786, in _launch_pavement

  File "paver-minilib.zip/paver/tasks.py", line 739, in _process_commands

  File "paver-minilib.zip/paver/tasks.py", line 653, in _parse_command_line

  File "paver-minilib.zip/paver/tasks.py", line 611, in _preparse

  File "paver-minilib.zip/paver/tasks.py", line 107, in get_task

  File "paver-minilib.zip/paver/setuputils.py", line 167, in get_task

  File "paver-minilib.zip/paver/setuputils.py", line 195, in _get_distribution

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 580, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 818, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 830, in obtain

    return installer(requirement)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 593, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 623, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 809, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1015, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1000, in run_setup

    run_setup(setup_script, args)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 47, in run_setup

    working_set.__init__()

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 430, in __init__

    self.add_entry(entry)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 444, in add_entry

    for dist in find_distributions(entry, True):

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 1745, in find_eggs_in_zip

    metadata = EggMetadata(importer)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 1710, in __init__

    self.zipinfo = build_zipmanifest(importer.archive)

  File "/home/graham/Virtual-Environments/readme-work/local/lib/python2.7/site-packages/pkg_resources.py", line 1477, in build_zipmanifest

    zfile = zipfile.ZipFile(path)

  File "/usr/lib/python2.7/zipfile.py", line 756, in __init__

    self.fp = open(file, modeDict[mode])

IOError: [Errno 2] No such file or directory: 'paver-minilib.zip'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/graham/Virtual-Environments/readme-work/build/irc
Storing debug log for failure in /home/graham/.pip/pip.log

**Comment by stephenmcd** [comment]
I didn't hit this on a brand new machine. I think it's machine specific, and a setup issue with one of the required libs (the irc lib I believe, but not entirely sure).

**Comment by 1stvamp** [comment]
Just wanted to add that on a fresh trusty VM in a virtualenv'd pip this error still occurs (and yes pip installing paver then fixes it).

**Comment by primordialstew** [comment]
I found this issue when Googling about getting this same error in my own project, I was able to resolve it by changing the generated `setup.py` to refer to the minilib archive with an absolute path:

```python
try:
    import paver.tasks
except ImportError:
    from os.path import abspath
    from os.path import exists
    minilib = "paver-minilib.zip"
    if exists(minilib):
        import sys
        sys.path.insert(0, abspath(minilib))
    import paver.tasks

paver.tasks.main()
```

Hope that might be helpful to you or the next person who finds this.

**Comment by mikerev** [comment]
Still exists..I'll put in a PR if it annoys me again.
